In [1]:
import pandas as pd

df = pd.read_csv("../data/atlantic_spain.csv")

df.head()

,date,position,song,artist,popularity,duration_ms,album_type,total_tracks,is_explicit,album_cover_url
0,18-05-2024,1,Supernova,Saiko,84,190909,single,1,False,https://i.scdn.co/image/ab67616d0000b273c3f5b9...
1,18-05-2024,2,EL TONTO,Lola Indigo,83,187986,album,11,False,https://i.scdn.co/image/ab67616d0000b273daab36...
2,18-05-2024,3,Acróstico,Shakira,81,170785,single,1,False,https://i.scdn.co/image/ab67616d0000b273bd6bbd...
3,18-05-2024,4,BESO,ROSALÍA & Rauw Alejandro,96,194543,single,3,False,https://i.scdn.co/image/ab67616d0000b2734d6cf0...
4,18-05-2024,5,El Merengue,Marshmello & Manuel Turizo,91,189668,single,1,False,https://i.scdn.co/image/ab67616d0000b273f40467...

In [2]:
df.shape

(27800, 10)

In [3]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 27800 entries, 0 to 27799
Data columns (total 10 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   date             27800 non-null  str
 1   position         27800 non-null  int64
 2   song             27800 non-null  str
 3   artist           27800 non-null  str
 4   popularity       27800 non-null  int64
 5   duration_ms      27800 non-null  int64
 6   album_type       27800 non-null  str
 7   total_tracks     27800 non-null  int64
 8   is_explicit      27800 non-null  bool
 9   album_cover_url  27800 non-null  str
dtypes: bool(1), int64(4), str(5)
memory usage: 4.8 MB

In [4]:
df.describe()

           position    popularity    duration_ms  total_tracks
count  27800.000000  27800.000000   27800.000000  27800.000000
mean      25.500000     81.123957  197473.678237      7.202554
std       14.431129     10.088455   43371.454913      7.683734
min        1.000000      0.000000   90613.000000      1.000000
25%       13.000000     76.000000  168594.000000      1.000000
50%       25.500000     82.000000  191254.000000      1.000000
75%       38.000000     87.000000  218119.000000     15.000000
max       50.000000    100.000000  555071.000000     49.000000

In [5]:
df.isnull().sum()

date               0
position           0
song               0
artist             0
popularity         0
duration_ms        0
album_type         0
total_tracks       0
is_explicit        0
album_cover_url    0
dtype: int64

In [7]:
df['date'] = pd.to_datetime(df['date'], format='%d-%m-%Y')

In [8]:
print("Duplicate rows:", df.duplicated().sum())

Duplicate rows: 15

In [9]:
df = df.drop_duplicates()

In [10]:
print("Duplicate rows:", df.duplicated().sum())

Duplicate rows: 0

In [11]:
df['song'] = df['song'].str.strip()

In [12]:
df['artist'] = df['artist'].str.strip()

In [13]:
df['song_id'] = (
    df['song'].str.lower().str.strip() +
    "_" +
    df['artist'].str.lower().str.strip()
)

In [14]:
df[['song_id', 'song', 'artist']].head()

,song_id,song,artist
0,supernova_saiko,Supernova,Saiko
1,el tonto_lola indigo,EL TONTO,Lola Indigo
2,acróstico_shakira,Acróstico,Shakira
3,beso_rosalía & rauw alejandro,BESO,ROSALÍA & Rauw Alejandro
4,el merengue_marshmello & manuel turizo,El Merengue,Marshmello & Manuel Turizo

In [15]:
df['duration_min'] = df['duration_ms'] / 60000

In [16]:
df.head()

,date,position,song,artist,popularity,duration_ms,album_type,total_tracks,is_explicit,album_cover_url,song_id,duration_min
0,2024-05-18,1,Supernova,Saiko,84,190909,single,1,False,https://i.scdn.co/image/ab67616d0000b273c3f5b9...,supernova_saiko,3.181817
1,2024-05-18,2,EL TONTO,Lola Indigo,83,187986,album,11,False,https://i.scdn.co/image/ab67616d0000b273daab36...,el tonto_lola indigo,3.133100
2,2024-05-18,3,Acróstico,Shakira,81,170785,single,1,False,https://i.scdn.co/image/ab67616d0000b273bd6bbd...,acróstico_shakira,2.846417
3,2024-05-18,4,BESO,ROSALÍA & Rauw Alejandro,96,194543,single,3,False,https://i.scdn.co/image/ab67616d0000b2734d6cf0...,beso_rosalía & rauw alejandro,3.242383
4,2024-05-18,5,El Merengue,Marshmello & Manuel Turizo,91,189668,single,1,False,https://i.scdn.co/image/ab67616d0000b273f40467...,el merengue_marshmello & manuel turizo,3.161133

In [17]:
df.to_csv("../data/atlantic_spain_cleaned.csv", index=False)

In [18]:
print(df.shape)

(27785, 12)