In [1]:
import pandas as pd

df = pd.read_csv("../data/atlantic_spain_cleaned.csv")

df['date'] = pd.to_datetime(df['date'])

In [2]:
print("Unique Songs :", df['song_id'].nunique())

Unique Songs : 575

In [3]:
entry_date = (
    df.groupby('song_id')['date']
      .min()
      .rename("entry_date")
)

In [4]:
exit_date = (
    df.groupby('song_id')['date']
      .max()
      .rename("exit_date")
)

In [5]:
lifecycle = pd.concat(
    [entry_date, exit_date],
    axis=1
)

lifecycle.head()

                                                   entry_date  exit_date
song_id
0 confianza_rvfv                                   2025-06-02 2025-06-23
1 de enero, puntacana_rels b                       2025-04-28 2025-04-28
1000cosas_lola indigo & manuel turizo              2025-03-10 2025-11-13
100xciento_foreign teck & eladio carrion & de l... 2025-04-30 2025-05-15
14 febreros_quevedo                                2025-11-24 2025-11-27

In [6]:
lifecycle['days_on_playlist'] = (
    lifecycle['exit_date'] -
    lifecycle['entry_date']
).dt.days + 1

In [7]:
best_rank = (
    df.groupby('song_id')['position']
      .min()
      .rename("best_rank")
)

lifecycle = lifecycle.join(best_rank)

In [8]:
worst_rank = (
    df.groupby('song_id')['position']
      .max()
      .rename("worst_rank")
)

lifecycle = lifecycle.join(worst_rank)

In [9]:
avg_rank = (
    df.groupby('song_id')['position']
      .mean()
      .rename("avg_rank")
)

lifecycle = lifecycle.join(avg_rank)

In [10]:
peak_popularity = (
    df.groupby('song_id')['popularity']
      .max()
      .rename("peak_popularity")
)

lifecycle = lifecycle.join(peak_popularity)

In [11]:
avg_popularity = (
    df.groupby('song_id')['popularity']
      .mean()
      .rename("avg_popularity")
)

lifecycle = lifecycle.join(avg_popularity)

In [12]:
lifecycle.head()

,entry_date,exit_date,days_on_playlist,best_rank,worst_rank,avg_rank,peak_popularity,avg_popularity
song_id,,,,,,,,
0 confianza_rvfv,2025-06-02,2025-06-23,22,23,42,29.650000,62,57.550000
"1 de enero, puntacana_rels b",2025-04-28,2025-04-28,1,45,45,45.000000,65,65.000000
1000cosas_lola indigo & manuel turizo,2025-03-10,2025-11-13,249,3,44,20.428571,81,76.171429
100xciento_foreign teck & eladio carrion & de la ghetto,2025-04-30,2025-05-15,16,13,42,28.181818,75,73.727273
14 febreros_quevedo,2025-11-24,2025-11-27,4,9,16,13.500000,68,65.750000

In [13]:
lifecycle.shape

(575, 8)