In [15]:
import pandas as pd
import numpy as np

from sklearn.model_selection import train_test_split

In [16]:
lifecycle = pd.read_csv(
    "../data/lifecycle_advanced_features.csv", index_col=0
)

lifecycle.head()

,song_id,entry_date,exit_date,days_on_playlist,best_rank,worst_rank,avg_rank,initial_rank,rank_improvement,rank_range,rank_volatility,avg_daily_rank_change,peak_popularity,avg_popularity,popularity_gap,playlist_entries,days_to_peak,stability_score
0,0 confianza_rvfv,2025-06-02,2025-06-23,22,23,42,29.650000,40,17,19,5.659412,2.210526,62,57.550000,4.450000,20,5,3.303595
1,"1 de enero, puntacana_rels b",2025-04-28,2025-04-28,1,45,45,45.000000,45,0,0,0.000000,NaN,65,65.000000,0.000000,1,0,1.000000
2,1000cosas_lola indigo & manuel turizo,2025-03-10,2025-11-13,249,3,44,20.428571,3,0,41,9.585679,1.102459,81,76.171429,4.828571,245,0,23.522345
3,100xciento_foreign teck & eladio carrion & de ...,2025-04-30,2025-05-15,16,13,42,28.181818,42,29,29,9.086453,11.700000,75,73.727273,1.272727,11,11,1.586286
4,14 febreros_quevedo,2025-11-24,2025-11-27,4,9,16,13.500000,9,0,7,3.316625,2.333333,68,65.750000,2.250000,4,0,0.926650

In [17]:
print("Rows :", lifecycle.shape[0])
print("Columns :", lifecycle.shape[1])

lifecycle.info()

Rows : 575
Columns : 18
<class 'pandas.DataFrame'>
RangeIndex: 575 entries, 0 to 574
Data columns (total 18 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   song_id                575 non-null    str
 1   entry_date             575 non-null    str
 2   exit_date              575 non-null    str
 3   days_on_playlist       575 non-null    int64
 4   best_rank              575 non-null    int64
 5   worst_rank             575 non-null    int64
 6   avg_rank               575 non-null    float64
 7   initial_rank           575 non-null    int64
 8   rank_improvement       575 non-null    int64
 9   rank_range             575 non-null    int64
 10  rank_volatility        575 non-null    float64
 11  avg_daily_rank_change  492 non-null    float64
 12  peak_popularity        575 non-null    int64
 13  avg_popularity         575 non-null    float64
 14  popularity_gap         575 non-null    float64
 15  playlist_entries       575 non-null    int64
 16  days_to_peak           575 non-null    int64
 17  stability_score        575 non-null    float64
dtypes: float64(6), int64(9), str(3)
memory usage: 108.1 KB

In [18]:
lifecycle.isnull().sum().sort_values(ascending=False)

avg_daily_rank_change    83
song_id                   0
entry_date                0
days_to_peak              0
playlist_entries          0
popularity_gap            0
avg_popularity            0
peak_popularity           0
rank_volatility           0
rank_range                0
rank_improvement          0
initial_rank              0
avg_rank                  0
worst_rank                0
best_rank                 0
days_on_playlist          0
exit_date                 0
stability_score           0
dtype: int64

## Missing Values

Only avg_daily_rank_change contains missing values.
These occur for songs appearing on a single playlist snapshot and are filled with 0.

In [19]:
lifecycle["avg_daily_rank_change"] = (
    lifecycle["avg_daily_rank_change"]
    .fillna(0)
)

In [20]:
lifecycle.isnull().sum()

song_id                  0
entry_date               0
exit_date                0
days_on_playlist         0
best_rank                0
worst_rank               0
avg_rank                 0
initial_rank             0
rank_improvement         0
rank_range               0
rank_volatility          0
avg_daily_rank_change    0
peak_popularity          0
avg_popularity           0
popularity_gap           0
playlist_entries         0
days_to_peak             0
stability_score          0
dtype: int64

In [21]:
drop_cols = [
    "song_id",
    "entry_date",
    "exit_date"
]

lifecycle = lifecycle.drop(columns=drop_cols)

In [22]:
lifecycle.columns

Index(['days_on_playlist', 'best_rank', 'worst_rank', 'avg_rank',
       'initial_rank', 'rank_improvement', 'rank_range', 'rank_volatility',
       'avg_daily_rank_change', 'peak_popularity', 'avg_popularity',
       'popularity_gap', 'playlist_entries', 'days_to_peak',
       'stability_score'],
      dtype='str')

In [23]:
target = "days_on_playlist"

In [24]:
X = lifecycle.drop(columns=[target])

y = lifecycle[target]

In [25]:
print(X.shape)
print(y.shape)

X.head()

(575, 14)
(575,)

,best_rank,worst_rank,avg_rank,initial_rank,rank_improvement,rank_range,rank_volatility,avg_daily_rank_change,peak_popularity,avg_popularity,popularity_gap,playlist_entries,days_to_peak,stability_score
0,23,42,29.650000,40,17,19,5.659412,2.210526,62,57.550000,4.450000,20,5,3.303595
1,45,45,45.000000,45,0,0,0.000000,0.000000,65,65.000000,0.000000,1,0,1.000000
2,3,44,20.428571,3,0,41,9.585679,1.102459,81,76.171429,4.828571,245,0,23.522345
3,13,42,28.181818,42,29,29,9.086453,11.700000,75,73.727273,1.272727,11,11,1.586286
4,9,16,13.500000,9,0,7,3.316625,2.333333,68,65.750000,2.250000,4,0,0.926650

In [26]:
X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42
)

In [27]:
print("Training Features :", X_train.shape)
print("Testing Features :", X_test.shape)

print("Training Labels :", y_train.shape)
print("Testing Labels :", y_test.shape)

Training Features : (460, 14)
Testing Features : (115, 14)
Training Labels : (460,)
Testing Labels : (115,)

In [28]:
X_train.to_csv("../data/X_train.csv", index=False)
X_test.to_csv("../data/X_test.csv", index=False)

y_train.to_csv("../data/y_train.csv", index=False)
y_test.to_csv("../data/y_test.csv", index=False)